# Generated by Django 3.2.8 on 2021-11-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
