# Generated by Django 3.2.8 on 2021-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211121_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exchange_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
