# Generated by Django 3.2.8 on 2021-11-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211122_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='exchange_rate',
            new_name='exchange_rate_eur',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='exchange_rate_usd',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
