# Generated by Django 3.2.8 on 2021-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211122_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate_eur',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate_usd',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
