# Generated by Django 3.2.8 on 2021-11-13 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('RATHER_NOT_SAY', 'Rather not say')], max_length=20, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='core.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile info',
                'verbose_name_plural': 'Profiles info',
            },
        ),
    ]
