# Generated by Django 3.2.8 on 2021-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profileinformation_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Rather not say', 'Rather not say')], max_length=20, null=True),
        ),
    ]
