# Generated by Django 3.2.8 on 2021-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211117_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
