# Generated by Django 3.2.8 on 2021-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profileinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='status',
            field=models.CharField(blank=True, default='My status', max_length=40, null=True),
        ),
    ]
