# Generated by Django 3.2.8 on 2021-11-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologyimages',
            name='topology_image',
            field=models.ImageField(blank=True, null=True, upload_to='network_topology/%Y/%m/%d/'),
        ),
    ]
