# Generated by Django 3.2.8 on 2021-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_topologyimages_topology_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologyimages',
            name='topology_image',
            field=models.FileField(blank=True, null=True, upload_to='network_topology/%Y/%m/%d/'),
        ),
    ]
