# Generated by Django 3.2.8 on 2021-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211121_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='topology_image',
            field=models.ImageField(blank=True, null=True, upload_to='network_topology/%Y/%m/%d/'),
        ),
    ]
